version: '3.8'
services:

  frontend:
    #stdin_open: true
    image: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000 # <<- WORKS WITHOUT JUST TAKES TIME!
    container_name: frontend
    environment:
      #- REACT_APP_BACKEND_URL=http://localhost:8080/api/
      - REACT_APP_BACKEND_URL=http://localhost:3001/
      - CI=true
      - PORT=3000
    depends_on:
      - backend

  backend:
    image: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:                # Declares the ports to publish
      - 3001:3001 # REMOVE later!!!
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/the_database
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 3456:27017 # remove later!!!
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./backend/mongo_data:/data/db

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: nginx
    depends_on:
      - frontend
      - backend
