version: '3.8'
services:

  frontend:
    stdin_open: true
    image: frontend-dev
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000 # <<- WORKS WITHOUT JUST TAKES TIME!
    container_name: frontend-dev
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    depends_on:
      - backend

  backend:
    image: backend-dev
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    ports:                # Declares the ports to publish
      - 3001:3001 # REMOVE later!!!
    container_name: backend-dev
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://root:example@mongodb:27017/the_database # MONGODB_URI !!!
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 3456:27017 # remove later!!!
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      #- ./backend/mongo_data:/data/db

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: nginx
    depends_on:
      - frontend
      - backend
