services:
  app:
    image: todoapp-front-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: todoapp-front-dev
  debug-helper:
    image: busybox