name: Scheduled health check
on:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.5
      with:
        url: https://reallyboringapp.herokuapp.com/health
        max-attempts: 3
        retry-delay: 5s
        retry-all: no
